# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
      name: "workstation-{{OSP_GUID}}.{{OSP_DOMAIN}}"
      group: workstation
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user


- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yaml 

