---
# vars file for osp.servers
cloud_name: openstack

osp_servers:
  - app1:
      name: app1
      image: rhel-guest
      key_name: ansible_ssh
      flavor: m1.medium
      security_group: apps
      net_name: int_network
      floating_ip_address: ext_network
      meta: group=apps-servers, deployment_name=QA
      userdata: |
                #!/bin/bash
                curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/openstack.pub 
                curl -o /tmp/openstack.pem http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
                cat /tmp/openstack.pem >> /home/cloud-user/.ssh/openstack.pem
                curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
                cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  - app2:
      name: app2
      image: rhel-guest
      key_name: ansible_ssh
      flavor: m1.medium
      security_group: apps
      net_name: int_network
      floating_ip_address: ext_network
      meta: group=apps_servers, deployment_name=QA
      userdata: |
                #!/bin/bash
                curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/openstack.pub 
                curl -o /tmp/openstack.pem http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
                cat /tmp/openstack.pem >> /home/cloud-user/.ssh/openstack.pem
                curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
                cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  - db:
      name: db
      image: rhel-guest
      key_name: ansible_ssh
      flavor: m1.medium
      security_group: db
      net_name: int_network
      floating_ip_address: ext_network
      meta: group=databases_servers, deployment_name=QA
      userdata: |
                #!/bin/bash
                curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/openstack.pub 
                curl -o /tmp/openstack.pem http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
                cat /tmp/openstack.pem >> /home/cloud-user/.ssh/openstack.pem
                curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
                cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
  - frontend:
      name: frontend
      image: rhel-guest
      key_name: ansible_ssh
      flavor: m1.medium
      security_group: frontend
      net_name: int_network
      floating_ip_address: ext_network
      meta: group=frontends_servers, deployment_name=QA
      userdata: |
                #!/bin/bash
                curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
                cat /tmp/openstack.pub >> /home/cloud-user/.ssh/openstack.pub 
                curl -o /tmp/openstack.pem http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem
                cat /tmp/openstack.pem >> /home/cloud-user/.ssh/openstack.pem
                curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
                cp /tmp/internal.repo /etc/yum.repos.d/internal.repo